### ISSUE TITLE
Switch to "asycnLib.constant()"

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/setup-instructor-resources#1]
https://github.com/byuitechops/setup-instructor-resources/blob/990d565b086b7b370a5b44c2c15603f7b5fb638f/main.js#L302

I didn't know apply was a util function in async - super cool. This situation calls for an `async.constant()` though, since it is the first function in the waterfall. It's functionally the same, but doesn't combine what's given to it with existing parameters from previous functions in the waterfall, like `apply` does. You could leave this as is, but its good to know the difference between the two.

**Comment by csammcgrath** [comment]
`async.constant()` looks more clean. I will go ahead and implement this.

**Comment by csammcgrath** [comment]
Fixed.
