### ISSUE TITLE
Instructor Resources Improvements

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/setup-instructor-resources#14]
A few improvements to be made. Reference the OCT course if you need to see what it looks like.

1. The Instructor Resources module should be unpublished.

2. The title of it should be "Instructor Resources (Do NOT Publish)".

3. All the items in Instructor Resources should be unpublished.

4. Course Maintenance Log needs to be under Standard Resources.

**Comment by csammcgrath** [comment]
1. Fixed.
2. Fixed.
3. Fixed.
4. Fixed.
