### ISSUE TITLE
setup-instructor-resources - "Release Notes" need to be put into "Standard Resources"

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/setup-instructor-resources#17]

**Comment by csammcgrath** [comment]
I am not able to replicate this issue. Are you able to?

**Comment by zachintosh** [comment]
It occurred during a conversion test for our weekly monday meeting with Bro. Moore's team. I believe we converted FDREL 324 for the test. Next time we are in the office together, we'll run FDREL 324 again and see if it happens again.

**Comment by csammcgrath** [comment]
This issue only happens in FDREL 324. Everywhere else, it works just fine. I am closing this for now. If this issue arises in more courses, this issue will be re-opened.
