### ISSUE TITLE
Course Maintenance Log

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/setup-instructor-resources#2]
https://github.com/byuitechops/setup-instructor-resources/blob/990d565b086b7b370a5b44c2c15603f7b5fb638f/main.js#L302

Go ahead and create it in the D2L gauntlet if you haven't already. We should be updating the canvas one soon. I can show you how to as well; just make sure you ask any time you need to update the canvas gauntlet it after I show you.

**Comment by csammcgrath** [comment]
Added Course Maintenance Log to D2L Gauntlet.
