### ISSUE TITLE
Remove setTimout

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/setup-instructor-resources#3]
https://github.com/byuitechops/setup-instructor-resources/blob/990d565b086b7b370a5b44c2c15603f7b5fb638f/main.js#L323

I (think) fixed the issue that caused the need for a timeout this morning. Run `npm update` and give it a shot... It probably won't work, but if it doesn't, let me know. And if it does, let me know.

**Comment by csammcgrath** [comment]
Done.
