### ISSUE TITLE
"modules_name" variable

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/setup-instructor-resources#5]
https://github.com/byuitechops/setup-instructor-resources/blob/990d565b086b7b370a5b44c2c15603f7b5fb638f/main.js#L330-L342

I'd recommend removing the `modules_name` variable and just switching line 339 to:

```js
if (module.name === 'Instructor Resources') {
// ...the rest
}```

**Comment by csammcgrath** [comment]
Fixed.
