### ISSUE TITLE
Old Comments

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/setup-instructor-resources#8]
https://github.com/byuitechops/setup-instructor-resources/blob/990d565b086b7b370a5b44c2c15603f7b5fb638f/main.js#L148-L151

With commented code, unless you're still in the same commit, it's best to remove it and just refer back to the old commit the code is in if you need to. I'm not good at living that principle, so don't look to my code as an example haha

**Comment by csammcgrath** [comment]
Fixed.
